spring:
    application:
        name: recall
    kafka:
        bootstrap-servers: 
            - localhost:29092
            - localhost:39092
            - localhost:49092
        consumer:
            group-id: my-recall-id
    output:
        ansi:
            enabled: always

logging:
  level:
    '[com.slope.recall]': debug

scheduled:
    cron:
        break-time: 0 0 12-19 * * MON-FRI
        message: 0 */10 9-12,14-18 * * MON-FRI

external-apis:
    github-user-url: "https://api.github.com/users/"