spring:
    application:
        name: recall
    kafka:
        bootstrap-servers:
            - localhost:9092 # convenient mode
            # - localhost:29092
            # - localhost:39092
            # - localhost:49092
        consumer:
            group-id: my-recall-id
    output:
        ansi:
            enabled: always

logging:
  level:
    '[com.slope.recall]': debug
    # netflix discovery
    '[com.netflix.discovery.shared.resolver]': warn

scheduled:
    cron:
        break-time: 0 0 12-19 * * MON-FRI
        message: 0 */10 9-12,14-18 * * MON-FRI

external-apis:
    github-user-url: "https://api.github.com/users/"

server:
    port: 8081

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8991/eureka
