spring:
    application:
        name: recall
    kafka:
        bootstrap-servers: 
            - localhost:29092
            - localhost:39092
            - localhost:49092
        consumer:
            group-id: my-recall-id
