# obselete 
# version: '3.1'

services:
  mysql:
    image: mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
      # required to login with vs code plugin
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
