# obselete 
# version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
    - 3306:3306
    volumes:
      - .\mysql\:/etc/mysql/conf.d/
    # replacing below with volumes because more conf
    # command: ['mysqld', '--lower_case_table_names=1', '--skip-log-bin'] # lower-case only works if new instance/container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
      # required to login with vs code plugin
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
